name:                correct-me
version:             0.1.0.0
github:              "mreluzeon/correct-me"
license:             GPL-3.0-or-later
author:              "Leonid Konontsov"
maintainer:          "me@nokono.ru"
copyright:           "2024 Konontsov Leonid"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mreluzeon/correct-me#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- servant-auth-server
- servant-auth
- http-media
- text
- containers
- bytestring
- time
- warp
- http-api-data
- hasql
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  correct-me-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correct-me

tests:
  correct-me-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - correct-me
